import React, { useEffect, useRef } from "react";
import { gsap } from "gsap";
import "../Marquee/Marquee.css";

export default function Marquee() {
    const marqueeRef = useRef(null);

    useEffect(() => {
        const ctx = gsap.context(() => {
            gsap.to(".marquee-track", {
                xPercent: -100, // move full width
                repeat: -1,     // infinite loop
                duration: 500,   // speed (adjust as needed)
                ease: "linear"
            });
        }, marqueeRef);

        return () => ctx.revert(); // cleanup on unmount
    }, []);

    return (
        <div className="marquee" ref={marqueeRef}>
            <div className="marquee-track">
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
                <span>TRUSTED BY OVER 80+ BRANDS ★★★★★</span>
            </div>
        </div>
    );
}
